services:
  aspire-dashboard:
    # 9.3 has a bug where metrics don't work with kabob-case service names
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.2
    ports:
      - "18888:18888"
      - "4317:18889"
    environment:
      ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
  postgres:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
