[package]
name = "service-common"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
opentelemetry = "0.30.0"
opentelemetry-semantic-conventions = "0.30.0"

[dev-dependencies]
opentelemetry_sdk = { version = "0.30.0", features = ["testing"] }
tokio = { version = "1.45.1", features = ["full"] }
tower = "0.5.2"
